# Generated by Django 5.2 on 2025-05-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
